openapi: 3.0.0
info:
  title: Bookstore API
  description: API for managing books
  version: 1.0.0
paths:
  /books:
    get:
      summary: Retrieve all books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Book added successfully
        '400':
          description: Invalid request body
  /books/{id}:
    get:
      summary: Get a single book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the book to retrieve
      responses:
        '200':
          description: A single book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
    put:
      summary: Update a book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the book to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Book updated successfully
        '400':
          description: Invalid request body
        '404':
          description: Book not found
    delete:
      summary: Delete a book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the book to delete
      responses:
        '200':
          description: Book deleted successfully
        '404':
          description: Book not found
components:
  schemas:
    Book:
      type: object
      properties:
        book_id:
          type: integer
        title:
          type: string
        author:
          type: string
        pub_date:
          type: string
          format: date
        num_pages:
          type: integer
